/**
 * @file cli_cmd.c
 * @author Sebastián Del Moral Gallardo.
 * @brief CLI commands implemented in system.
 *
 */

/* Includes ------------------------------------------------------------------*/

#include "cli_cmd.h"
#include "cli_task.h"
#include "FreeRTOS.h"
#include "FreeRTOS_CLI.h"
#include "sys_mcu.h"
#ifdef USE_USER_ASSERT
#include "user_error.h"
#endif

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
#ifdef USE_USER_ASSERT
#define USER_ASSERT(A)      ERR_ASSERT(A)
#else
#define USER_ASSERT(A)      (void)(A)
#endif

/* Private function prototypes -----------------------------------------------*/

/**
 * @brief  Force reset device.
 * @param  pcWriteBuffer
 * @param  xWriteBufferLen
 * @param  pcCommandString
 * @retval pdFALSE, pdTRUE
 */
static BaseType_t userReset(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString);

/**
 * @brief  Force assert generated by user.
 * @param  pcWriteBuffer
 * @param  xWriteBufferLen
 * @param  pcCommandString
 * @retval pdFALSE, pdTRUE
 */
static BaseType_t userAssert(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString);

/**
 * @brief  Force hard fault.
 * @param  pcWriteBuffer
 * @param  xWriteBufferLen
 * @param  pcCommandString
 * @retval pdFALSE, pdTRUE
 */
static BaseType_t userHardFault(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString);

/**
 * @brief  Get current system time.
 * @param  pcWriteBuffer
 * @param  xWriteBufferLen
 * @param  pcCommandString
 * @retval pdFALSE, pdTRUE
 */
static BaseType_t userGetTime(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString);

/* Private variables ---------------------------------------------------------*/

static const CLI_Command_Definition_t xUserReset = {
    "reset",
    "reset:\tForce device reset",
    userReset,
    0
};

static const CLI_Command_Definition_t xUserAssert = {
    "assert",
    "assert:\tForce assert error",
    userAssert,
    0
};

static const CLI_Command_Definition_t xUserFault = {
    "fault",
    "fault:\tForce hardfaul",
    userHardFault,
    0
};

static const CLI_Command_Definition_t xUserTime = {
    "time",
    "time:\tGet system time",
    userGetTime,
    0
};

/* Callbacks -----------------------------------------------------------------*/
/* Private application code --------------------------------------------------*/

static BaseType_t userReset(char *pcWriteBuffer,
        size_t xWriteBufferLen,
        const char *pcCommandString)
{
    vCliPrintf(CLI_TASK_NAME, "OK");
    SYS_Reset();
    return pdFALSE;
}

static BaseType_t userAssert(char *pcWriteBuffer,
        size_t xWriteBufferLen,
        const char *pcCommandString)
{
    ERR_ASSERT(0);
    return pdFALSE;
}

static BaseType_t userHardFault(char *pcWriteBuffer,
        size_t xWriteBufferLen,
        const char *pcCommandString)
{
    __builtin_trap();
    return pdFALSE;
}

static BaseType_t userGetTime(char *pcWriteBuffer,
        size_t xWriteBufferLen,
        const char *pcCommandString)
{
    vCliPrintf(CLI_TASK_NAME, "Time: %u", xTaskGetTickCount());
    vCliPrintf(CLI_TASK_NAME, "OK");
    return pdFALSE;
}

/* Public application code ---------------------------------------------------*/

void cli_cmd_init(void)
{
    (void)FreeRTOS_CLIRegisterCommand(&xUserReset);
    (void)FreeRTOS_CLIRegisterCommand(&xUserAssert);
    (void)FreeRTOS_CLIRegisterCommand(&xUserFault);
    (void)FreeRTOS_CLIRegisterCommand(&xUserTime);
}

/* EOF */
