/**
 * @file cli_cmd.c
 * @author Sebastián Del Moral Gallardo.
 * @brief CLI commands implemented in system.
 *
 */

/* Includes ------------------------------------------------------------------*/

#include "cli_cmd.h"
#include "cli_task.h"
#include "FreeRTOS.h"
#include "FreeRTOS_CLI.h"
#include "sys_mcu.h"
#include "dac_mcp4728.h"
#include "printf.h"

/* TODO: change atoi for ligher version */
#include <stdlib.h>

#ifdef USE_USER_ASSERT
#include "user_error.h"
#endif

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
#ifdef USE_USER_ASSERT
#define USER_ASSERT(A)      ERR_ASSERT(A)
#else
#define USER_ASSERT(A)      (void)(A)
#endif

/* Private function prototypes -----------------------------------------------*/

/**
 * @brief  Force value in dac.
 * @param  pcWriteBuffer
 * @param  xWriteBufferLen
 * @param  pcCommandString
 * @retval pdFALSE, pdTRUE
 */
static BaseType_t userDacSetVal(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString);

/**
 * @brief  Force reset device.
 * @param  pcWriteBuffer
 * @param  xWriteBufferLen
 * @param  pcCommandString
 * @retval pdFALSE, pdTRUE
 */
static BaseType_t userReset(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString);

/**
 * @brief  Force assert generated by user.
 * @param  pcWriteBuffer
 * @param  xWriteBufferLen
 * @param  pcCommandString
 * @retval pdFALSE, pdTRUE
 */
static BaseType_t userAssert(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString);

/**
 * @brief  Force hard fault.
 * @param  pcWriteBuffer
 * @param  xWriteBufferLen
 * @param  pcCommandString
 * @retval pdFALSE, pdTRUE
 */
static BaseType_t userHardFault(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString);

/**
 * @brief  Get current system time.
 * @param  pcWriteBuffer
 * @param  xWriteBufferLen
 * @param  pcCommandString
 * @retval pdFALSE, pdTRUE
 */
static BaseType_t userGetTime(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString);

/* Private variables ---------------------------------------------------------*/

static const CLI_Command_Definition_t xDacSetVal = {
    "dacSetVal",
    "dacSetVal:\tSet value on DAC channel: <Channel 0-3> <Dac Value 0-4096>",
    userDacSetVal,
    2U
};

static const CLI_Command_Definition_t xUserReset = {
    "reset",
    "reset:\tForce device reset",
    userReset,
    0
};

static const CLI_Command_Definition_t xUserAssert = {
    "assert",
    "assert:\tForce assert error",
    userAssert,
    0
};

static const CLI_Command_Definition_t xUserFault = {
    "fault",
    "fault:\tForce hardfaul",
    userHardFault,
    0
};

static const CLI_Command_Definition_t xUserTime = {
    "time",
    "time:\tGet system time",
    userGetTime,
    0
};

/* Callbacks -----------------------------------------------------------------*/
/* Private application code --------------------------------------------------*/

static BaseType_t userDacSetVal(char *pcWriteBuffer, 
        size_t xWriteBufferLen, 
        const char *pcCommandString)
{
    uint8_t u8DacChannel;
    uint16_t u16DacValue;
    char *pcParameter1;
    char *pcParameter2;
    BaseType_t xParameter1StringLength;
    BaseType_t xParameter2StringLength;

    /* Get cmd parameters */
    pcParameter1 = (char *)FreeRTOS_CLIGetParameter(pcCommandString, 1U, &xParameter1StringLength);
    pcParameter2 = (char *)FreeRTOS_CLIGetParameter(pcCommandString, 2U, &xParameter2StringLength);
    pcParameter1[xParameter1StringLength] = 0x00;
    pcParameter2[xParameter2StringLength] = 0x00;
    u8DacChannel = (uint8_t)atoi(pcParameter1);
    u16DacValue = (uint16_t)atoi(pcParameter2);

    /* Check parameters */
    if ((u8DacChannel < (uint8_t)DAC_CH_MAX_NUM) && (u16DacValue < DAC_MAX_COUNT))
    {
        DacMcp4728_t xDacHandler = { 
            .u8Address = DAC_BASE_ADDR,
            .u8IfPort = 0,
            .eVref = DAC_VREF_INT,
            .eGain = DAC_GAIN_1,
            .ePd = DAC_PD_NORMAL
        };
        (void)DacUpdateChannel(&xDacHandler, u8DacChannel, u16DacValue);
        vCliPrintf(CLI_TASK_NAME, "CH %02d - VALUE %d", u8DacChannel, u16DacValue);
        vCliPrintf(CLI_TASK_NAME, "OK");
    }
    else
    {
        vCliPrintf(CLI_TASK_NAME, "Invalid parameters");
        vCliPrintf(CLI_TASK_NAME, "ERROR");
    }
    return pdFALSE;
}

static BaseType_t userReset(char *pcWriteBuffer,
        size_t xWriteBufferLen,
        const char *pcCommandString)
{
    vCliPrintf(CLI_TASK_NAME, "OK");
    SYS_Reset();
    return pdFALSE;
}

static BaseType_t userAssert(char *pcWriteBuffer,
        size_t xWriteBufferLen,
        const char *pcCommandString)
{
    ERR_ASSERT(0);
    return pdFALSE;
}

static BaseType_t userHardFault(char *pcWriteBuffer,
        size_t xWriteBufferLen,
        const char *pcCommandString)
{
    __builtin_trap();
    return pdFALSE;
}

static BaseType_t userGetTime(char *pcWriteBuffer,
        size_t xWriteBufferLen,
        const char *pcCommandString)
{
    vCliPrintf(CLI_TASK_NAME, "Time: %u", xTaskGetTickCount());
    vCliPrintf(CLI_TASK_NAME, "OK");
    return pdFALSE;
}

/* Public application code ---------------------------------------------------*/

void cli_cmd_init(void)
{
    (void)FreeRTOS_CLIRegisterCommand(&xDacSetVal);
    (void)FreeRTOS_CLIRegisterCommand(&xUserReset);
    (void)FreeRTOS_CLIRegisterCommand(&xUserAssert);
    (void)FreeRTOS_CLIRegisterCommand(&xUserFault);
    (void)FreeRTOS_CLIRegisterCommand(&xUserTime);
}

/* EOF */
